# See the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    target-branch: "dev"
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    target-branch: "dev"
